name: 抖音内容自动生成
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 运行生成
        run: python main.py
      - name: 保存文件
        run: |
          git config --global user.name "auto"
          git config --global user.email "auto@auto.com"
          git add output.txt
          git commit -m "自动更新内容"
          git push
