name: 抖音自动发视频
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */2 * * *'  # 每2小时自动运行一次

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装依赖
        run: pip install -r requirements.txt
      - name: 启动自动发布
        run: python main.py
